sonar.projectKey=finansale-mobile
sonar.projectName=Finansale Mobile
sonar.projectVersion=1.0

sonar.sources=app,src,components 
sonar.host.url=http://localhost:9000
sonar.login=admin
sonar.password=adminn
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**, .expo/**, web-build/**