name: EAS OTA Update (Preview)

# ¿Cuándo se ejecuta esto?
on:
  push:
    branches:
      - master
      - chore/configurarion-ota-ci-cd

jobs:
  publish-update:
    name: Publicar Actualización OTA
    runs-on: ubuntu-latest

    steps:
      # 1. Clona tu código en el servidor de GitHub
      - name: 🏗 Configurar repositorio
        uses: actions/checkout@v3

      # 2. Prepara Node.js
      - name: 🏗 Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      # 3. Instala Expo y se loguea en tu cuenta usando un Token Secreto
      - name: 🏗 Configurar Expo y EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      # 4. Instala tus librerías (node_modules)
      - name: 📦 Instalar dependencias
        run: npm install

      # 5. ¡LA MAGIA! Envía la actualización a los celulares
      - name: 🚀 Enviar Actualización OTA (Over-The-Air)
        run: |
          eas update --auto --branch preview --message "Actualización automática CI/CD: ${{ github.event.head_commit.message }}"
