name: EAS OTA Update (Preview)

on:
  push:
    branches:
      - master
      - chore/configurarion-ota-ci-cd

jobs:
  publish-update:
    name: Publicar Actualización OTA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Publish OTA update
        run: |
          eas update \
            --branch preview \
            --message "Actualización automática CI/CD: ${{ github.event.head_commit.message }}" \
            --environment preview \
            --non-interactive
